joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Wheel motors (velocity)
front_left_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel_fl_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

front_right_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel_fr_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

center_left_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel_cl_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

center_right_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel_cr_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

rear_left_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel_rl_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

rear_right_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel_rr_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

# Steering (position)
front_left_steer_controller:
  type: position_controllers/JointPositionController
  joint: steer_fl_joint
  pid: {p: 50.0, i: 0.0, d: 1.0}

front_right_steer_controller:
  type: position_controllers/JointPositionController
  joint: steer_fr_joint
  pid: {p: 50.0, i: 0.0, d: 1.0}

rear_left_steer_controller:
  type: position_controllers/JointPositionController
  joint: steer_rl_joint
  pid: {p: 50.0, i: 0.0, d: 1.0}

rear_right_steer_controller:
  type: position_controllers/JointPositionController
  joint: steer_rr_joint
  pid: {p: 50.0, i: 0.0, d: 1.0}

# Arm (effort or position)
arm_joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_joint1
  pid: {p: 40.0, i: 0.1, d: 2.0}

arm_joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_joint2
  pid: {p: 40.0, i: 0.1, d: 2.0}

arm_joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_joint3
  pid: {p: 40.0, i: 0.1, d: 2.0}

arm_joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_joint4
  pid: {p: 40.0, i: 0.1, d: 2.0}

arm_joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_joint5
  pid: {p: 40.0, i: 0.1, d: 2.0}
